# Default configuration for af-consul-ts
# Override these values in local.yaml

consul:
  check:
    interval: "10s"
    timeout: "5s"
    deregistercriticalserviceafter: "3m"
  agent:
    reg:
      host: "localhost"
      port: 8500
      secure: false
    dev:
      dc: "dc-dev"
      host: "localhost"
      port: 8500
      secure: false
    prd:
      dc: "dc-prd"
      host: "localhost"
      port: 8500
      secure: false
  service:
    enable: true
    name: "af-consul-test"
    instance: "test"
    version: "0.0.1"
    description: "AF-CONSUL TEST"
    tags:
      - "af"
      - "consul"
      - "test"
    meta:
      CONSUL_TEST: "12345"
      line_yellow: "straight"
    host: null
    port: 10000
  envCode:
    prod: "prd-env"
    dev: "dev-env"

webServer:
  host: "0.0.0.0"
  port: 10000

accessPoints:
  wso2siAPI:
    title: "WSO2 SI API"
    consulServiceName: "dev01-wso2si-d2"
    host: null
    port: 9443
    protocol: "https"
    user: "admin"
    pass: "admin"
  wso2siParams:
    title: "WSO2 SI Params"
    consulServiceName: "dev01-wso2si-d2"
    host: null
    port: 9901
  wso2toolingAPI:
    title: "WSO2 Tooling API"
    consulServiceName: "dev01-wso2tooling-d2"
    host: null
    port: 9390
    user: "admin"
    pass: "admin"
  wso2toolingParams:
    title: "WSO2 Tooling Params"
    consulServiceName: "dev01-wso2tooling-d2"
    host: null
    port: 9902
